name: Sadew-MD Bot Runner

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: 
  schedule:
    - cron: "0 */5 * * *" # පැය 5න් 5ට ඔටෝ රීස්ටාර්ට් වේ (GitHub ලිමිට් එක පැනීමට)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install FFmpeg & ImageMagick (For Media & Stickers)
      run: |
        sudo apt-get update
        sudo apt-get install ffmpeg imagemagick -y

    - name: Install Project Dependencies
      run: npm install

    - name: Start Bot and Permanent Web Link
      env:
        NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
      run: |
        npm install -g concurrently ngrok
        ngrok config add-authtoken $NGROK_AUTHTOKEN
        concurrently "npm start" "ngrok http --domain=undertone-stylishly-opponent.ngrok-free.dev 8000"
